general_settings:
  master_key: sk-1234
  database_url: "os.environ/DATABASE_URL" # Picks up the URL from Docker
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  
model_list:
  - model_name: master
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"
      max_parallel_requests: 2
      temperature: 0.0
      supports_streaming: true
      extra_body:
        provider:
          require_parameters: true

  - model_name: github_summarizer
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"
      max_parallel_requests: 20
      temperature: 0.0
      supports_streaming: true
      extra_body:
        provider:
          require_parameters: true

  - model_name: profile_synthesizer
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"
      max_parallel_requests: 2
      temperature: 0.3
      supports_streaming: true
      extra_body:
        provider:
          require_parameters: true

  - model_name: papers_ranker
    litellm_params:
      model: openrouter/nvidia/nemotron-3-nano-30b-a3b
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"
      max_parallel_requests: 20
      temperature: 0.0
      supports_streaming: true
      extra_body:
        provider:
          require_parameters: true

